project:
  type: website
  output-dir: docs

website: 
  title: "<img src='/images/logos/logo_test.svg' alt='michael demsko jr logo' id='navbar-logo'/>"
  navbar:
    tools:
      - icon: list
        menu:
         - text: about
           href: about.qmd
         - text: ideas
           href: /ideas/
         - text: music
           href: /music/
         - text: writing
           href: /writing/
         - text: data
           href: /data/
         - text: design
           href: /design/
         - text: photo
           href: /photo/
    left:
      - href: index.qmd
        text: "<span id='navbar-title'>michael demsko jr</span>"


format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true

editor: visual

